import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReactQueryProviders from "@/components/providers/ReactQueryProvider";
import { Provider } from "react-redux";
import "./globals.css";
import { store } from "@/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProviders>
          <Provider store={store}>{children}</Provider>
        </ReactQueryProviders>
      </body>
    </html>
  );
}
